<?php

use App\Http\Controllers\CentroPageController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return auth()->check()
        ? redirect()->route('dashboard')
        : redirect()->route('login');
});

Route::get('/dashboard', [CentroPageController::class, 'dashboard'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::patch('/dashboard/widgets', [CentroPageController::class, 'updateDashboardWidgets'])->name('dashboard.widgets.update');
    Route::patch('/dashboard/note', [CentroPageController::class, 'updateDashboardNote'])->name('dashboard.note.update');
    Route::get('/clients', [CentroPageController::class, 'index'])->defaults('section', 'clients')->name('clients.index');
    Route::post('/clients', [CentroPageController::class, 'store'])->defaults('section', 'clients')->name('clients.store');
    Route::get('/clients/{id}', [CentroPageController::class, 'show'])->defaults('section', 'clients')->name('clients.show');
    Route::put('/clients/{id}', [CentroPageController::class, 'update'])->defaults('section', 'clients')->name('clients.update');
    Route::post('/clients/{id}/contacts', [CentroPageController::class, 'storeClientContact'])->name('clients.contacts.store');
    Route::put('/clients/{clientId}/contacts/{contactId}', [CentroPageController::class, 'updateClientContact'])->name('clients.contacts.update');
    Route::delete('/clients/{clientId}/contacts/{contactId}', [CentroPageController::class, 'destroyClientContact'])->name('clients.contacts.destroy');
    Route::post('/clients/{clientId}/services/{serviceId}', [CentroPageController::class, 'attachClientService'])->name('clients.services.attach');
    Route::delete('/clients/{clientId}/services/{serviceId}', [CentroPageController::class, 'detachClientService'])->name('clients.services.detach');
    Route::post('/clients/{clientId}/subscriptions', [CentroPageController::class, 'storeSubscription'])->name('clients.subscriptions.store');
    Route::put('/clients/{clientId}/subscriptions/{subscriptionId}', [CentroPageController::class, 'updateSubscription'])->name('clients.subscriptions.update');
    Route::patch('/clients/{clientId}/subscriptions/{subscriptionId}/active', [CentroPageController::class, 'toggleSubscription'])->name('clients.subscriptions.active');
    Route::post('/clients/{clientId}/subscriptions/{subscriptionId}/generate', [CentroPageController::class, 'generateSubscriptionDocument'])->name('clients.subscriptions.generate');
    Route::delete('/clients/{clientId}/subscriptions/{subscriptionId}', [CentroPageController::class, 'destroySubscription'])->name('clients.subscriptions.destroy');
    Route::delete('/clients/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'clients')->name('clients.destroy');
    Route::get('/projects', [CentroPageController::class, 'index'])->defaults('section', 'projects')->name('projects.index');
    Route::post('/projects', [CentroPageController::class, 'store'])->defaults('section', 'projects')->name('projects.store');
    Route::get('/projects/{id}', [CentroPageController::class, 'show'])->defaults('section', 'projects')->name('projects.show');
    Route::put('/projects/{id}', [CentroPageController::class, 'update'])->defaults('section', 'projects')->name('projects.update');
    Route::post('/projects/{id}/sections', [CentroPageController::class, 'storeProjectSection'])->name('projects.sections.store');
    Route::put('/projects/{projectId}/sections/{sectionId}', [CentroPageController::class, 'updateProjectSection'])->name('projects.sections.update');
    Route::post('/projects/{projectId}/sections/{sectionId}/duplicate', [CentroPageController::class, 'duplicateProjectSection'])->name('projects.sections.duplicate');
    Route::delete('/projects/{projectId}/sections/{sectionId}', [CentroPageController::class, 'destroyProjectSection'])->name('projects.sections.destroy');
    Route::put('/projects/{id}/tasks/reorder', [CentroPageController::class, 'reorderProjectTasks'])->name('projects.tasks.reorder');
    Route::post('/projects/{id}/messages', [CentroPageController::class, 'storeProjectMessage'])->name('projects.messages.store');
    Route::post('/projects/{id}/files', [CentroPageController::class, 'storeProjectFile'])->name('projects.files.store');
    Route::get('/projects/{projectId}/files/{fileId}', [CentroPageController::class, 'downloadProjectFile'])->name('projects.files.download');
    Route::delete('/projects/{projectId}/files/{fileId}', [CentroPageController::class, 'destroyProjectFile'])->name('projects.files.destroy');
    Route::put('/projects/{id}/followers', [CentroPageController::class, 'syncProjectFollowers'])->name('projects.followers.sync');
    Route::delete('/projects/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'projects')->name('projects.destroy');
    Route::get('/tasks', [CentroPageController::class, 'index'])->defaults('section', 'tasks')->name('tasks.index');
    Route::post('/tasks', [CentroPageController::class, 'store'])->defaults('section', 'tasks')->name('tasks.store');
    Route::get('/tasks/{id}', [CentroPageController::class, 'show'])->defaults('section', 'tasks')->name('tasks.show');
    Route::put('/tasks/{id}', [CentroPageController::class, 'update'])->defaults('section', 'tasks')->name('tasks.update');
    Route::post('/tasks/{id}/comments', [CentroPageController::class, 'storeTaskComment'])->name('tasks.comments.store');
    Route::put('/tasks/{taskId}/comments/{commentId}', [CentroPageController::class, 'updateTaskComment'])->name('tasks.comments.update');
    Route::delete('/tasks/{taskId}/comments/{commentId}', [CentroPageController::class, 'destroyTaskComment'])->name('tasks.comments.destroy');
    Route::post('/tasks/{id}/subtasks', [CentroPageController::class, 'storeSubtask'])->name('tasks.subtasks.store');
    Route::put('/tasks/{id}/subtasks/reorder', [CentroPageController::class, 'reorderSubtasks'])->name('tasks.subtasks.reorder');
    Route::post('/tasks/{id}/duplicate', [CentroPageController::class, 'duplicateTask'])->name('tasks.duplicate');
    Route::patch('/tasks/{id}/schedule', [CentroPageController::class, 'updateTaskSchedule'])->name('tasks.schedule.update');
    Route::patch('/tasks/{id}/status', [CentroPageController::class, 'updateTaskStatus'])->name('tasks.status.update');
    Route::put('/tasks/{id}/people/{type}', [CentroPageController::class, 'syncTaskPeople'])->name('tasks.people.sync');
    Route::put('/tasks/{id}/dependencies', [CentroPageController::class, 'syncTaskDependencies'])->name('tasks.dependencies.sync');
    Route::delete('/tasks/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'tasks')->name('tasks.destroy');
    Route::get('/calendar', [CentroPageController::class, 'index'])->defaults('section', 'calendar')->name('calendar.index');
    Route::get('/absences', [CentroPageController::class, 'index'])->defaults('section', 'absences')->name('absences.index');
    Route::get('/absences/{id}', [CentroPageController::class, 'show'])->defaults('section', 'absences')->name('absences.show');
    Route::put('/absences/{id}', [CentroPageController::class, 'updateAbsence'])->name('absences.update');
    Route::get('/absences/{id}/medical-document', [CentroPageController::class, 'downloadAbsenceMedicalDocument'])->name('absences.medical-document.download');
    Route::post('/absences/{id}/medical-document', [CentroPageController::class, 'updateAbsenceMedicalDocument'])->name('absences.medical-document.update');
    Route::patch('/absences/{id}/status', [CentroPageController::class, 'updateAbsenceStatus'])->name('absences.status.update');
    Route::delete('/absences/{id}', [CentroPageController::class, 'destroyAbsence'])->name('absences.destroy');
    Route::get('/documents', [CentroPageController::class, 'companyDocuments'])->name('documents.index');
    Route::post('/documents', [CentroPageController::class, 'storeCompanyDocument'])->name('documents.store');
    Route::get('/documents/users/{userId}', [CentroPageController::class, 'showCompanyDocumentsUser'])->name('documents.users.show');
    Route::get('/documents/{id}', [CentroPageController::class, 'showCompanyDocument'])->name('documents.show');
    Route::get('/documents/{id}/file', [CentroPageController::class, 'viewCompanyDocumentFile'])->name('documents.file');
    Route::post('/documents/{id}/read', [CentroPageController::class, 'markCompanyDocumentRead'])->name('documents.read');
    Route::delete('/documents/{id}', [CentroPageController::class, 'destroyCompanyDocument'])->name('documents.destroy');
    Route::post('/document-groups', [CentroPageController::class, 'storeDocumentGroup'])->name('document-groups.store');
    Route::put('/document-groups/{id}', [CentroPageController::class, 'updateDocumentGroup'])->name('document-groups.update');
    Route::delete('/document-groups/{id}', [CentroPageController::class, 'destroyDocumentGroup'])->name('document-groups.destroy');
    Route::get('/passwords', [CentroPageController::class, 'passwords'])->name('passwords.index');
    Route::post('/passwords/vaults', [CentroPageController::class, 'storePasswordVault'])->name('passwords.vaults.store');
    Route::put('/passwords/vaults/{id}', [CentroPageController::class, 'updatePasswordVault'])->name('passwords.vaults.update');
    Route::delete('/passwords/vaults/{id}', [CentroPageController::class, 'destroyPasswordVault'])->name('passwords.vaults.destroy');
    Route::post('/passwords/groups', [CentroPageController::class, 'storePasswordGroup'])->name('passwords.groups.store');
    Route::put('/passwords/groups/{id}', [CentroPageController::class, 'updatePasswordGroup'])->name('passwords.groups.update');
    Route::delete('/passwords/groups/{id}', [CentroPageController::class, 'destroyPasswordGroup'])->name('passwords.groups.destroy');
    Route::post('/passwords/items', [CentroPageController::class, 'storePasswordItem'])->name('passwords.items.store');
    Route::put('/passwords/items/{id}', [CentroPageController::class, 'updatePasswordItem'])->name('passwords.items.update');
    Route::post('/passwords/items/{id}/reveal', [CentroPageController::class, 'revealPasswordItem'])->name('passwords.items.reveal');
    Route::delete('/passwords/items/{id}', [CentroPageController::class, 'destroyPasswordItem'])->name('passwords.items.destroy');
    Route::get('/notifications', [CentroPageController::class, 'notifications'])->name('notifications.index');
    Route::get('/push/enable', [CentroPageController::class, 'enablePush'])->name('push.enable');
    Route::post('/push/test', [CentroPageController::class, 'testPush'])->name('push.test');
    Route::post('/push-subscriptions', [CentroPageController::class, 'storePushSubscription'])->name('push-subscriptions.store');
    Route::patch('/notifications/read-all', [CentroPageController::class, 'markAllNotificationsRead'])->name('notifications.read-all');
    Route::patch('/notifications/{id}/read', [CentroPageController::class, 'markNotificationRead'])->name('notifications.read');
    Route::patch('/notifications/{id}/restore', [CentroPageController::class, 'restoreNotification'])->name('notifications.restore');
    Route::delete('/notifications', [CentroPageController::class, 'archiveAllNotifications'])->name('notifications.destroy-all');
    Route::delete('/notifications/{id}', [CentroPageController::class, 'archiveNotification'])->name('notifications.destroy');
    Route::get('/updates/social', [CentroPageController::class, 'index'])->defaults('section', 'updates-social')->name('updates.social');
    Route::post('/updates/social', [CentroPageController::class, 'store'])->defaults('section', 'updates-social')->name('updates-social.store');
    Route::put('/updates/social/{id}', [CentroPageController::class, 'update'])->defaults('section', 'updates-social')->name('updates-social.update');
    Route::delete('/updates/social/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'updates-social')->name('updates-social.destroy');
    Route::get('/updates/newsletter', [CentroPageController::class, 'index'])->defaults('section', 'updates-newsletter')->name('updates.newsletter');
    Route::post('/updates/newsletter', [CentroPageController::class, 'store'])->defaults('section', 'updates-newsletter')->name('updates-newsletter.store');
    Route::put('/updates/newsletter/{id}', [CentroPageController::class, 'update'])->defaults('section', 'updates-newsletter')->name('updates-newsletter.update');
    Route::delete('/updates/newsletter/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'updates-newsletter')->name('updates-newsletter.destroy');
    Route::get('/updates/seo', [CentroPageController::class, 'index'])->defaults('section', 'updates-seo')->name('updates.seo');
    Route::post('/updates/seo', [CentroPageController::class, 'store'])->defaults('section', 'updates-seo')->name('updates-seo.store');
    Route::put('/updates/seo/{id}', [CentroPageController::class, 'update'])->defaults('section', 'updates-seo')->name('updates-seo.update');
    Route::delete('/updates/seo/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'updates-seo')->name('updates-seo.destroy');
    Route::get('/updates/adv', [CentroPageController::class, 'index'])->defaults('section', 'updates-adv')->name('updates.adv');
    Route::post('/updates/adv', [CentroPageController::class, 'store'])->defaults('section', 'updates-adv')->name('updates-adv.store');
    Route::put('/updates/adv/{id}', [CentroPageController::class, 'update'])->defaults('section', 'updates-adv')->name('updates-adv.update');
    Route::delete('/updates/adv/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'updates-adv')->name('updates-adv.destroy');
    Route::get('/billing', [CentroPageController::class, 'index'])->defaults('section', 'billing')->name('billing.index');
    Route::post('/billing', [CentroPageController::class, 'store'])->defaults('section', 'billing')->name('billing.store');
    Route::get('/billing/{id}', [CentroPageController::class, 'show'])->defaults('section', 'billing')->name('billing.show');
    Route::put('/billing/{id}', [CentroPageController::class, 'update'])->defaults('section', 'billing')->name('billing.update');
    Route::put('/billing/{id}/header', [CentroPageController::class, 'updateDocumentHeader'])->name('billing.header.update');
    Route::post('/billing/{id}/issue', [CentroPageController::class, 'issueDocument'])->name('billing.issue');
    Route::post('/billing/{id}/duplicate', [CentroPageController::class, 'duplicateDocument'])->name('billing.duplicate');
    Route::post('/billing/{id}/convert/{type}', [CentroPageController::class, 'convertDocument'])->name('billing.convert');
    Route::get('/billing/{id}/pdf', [CentroPageController::class, 'downloadDocumentPdf'])->name('billing.pdf');
    Route::get('/billing/{id}/xml', [CentroPageController::class, 'downloadDocumentXml'])->name('billing.xml');
    Route::post('/billing/{id}/email', [CentroPageController::class, 'sendDocumentEmail'])->name('billing.email');
    Route::post('/billing/{id}/lines', [CentroPageController::class, 'storeDocumentLine'])->name('billing.lines.store');
    Route::put('/billing/{documentId}/lines/{lineId}', [CentroPageController::class, 'updateDocumentLine'])->name('billing.lines.update');
    Route::delete('/billing/{documentId}/lines/{lineId}', [CentroPageController::class, 'destroyDocumentLine'])->name('billing.lines.destroy');
    Route::post('/billing/{id}/payments', [CentroPageController::class, 'storeDocumentPayment'])->name('billing.payments.store');
    Route::put('/billing/{documentId}/payments/{paymentId}', [CentroPageController::class, 'updateDocumentPayment'])->name('billing.payments.update');
    Route::delete('/billing/{documentId}/payments/{paymentId}', [CentroPageController::class, 'destroyDocumentPayment'])->name('billing.payments.destroy');
    Route::delete('/billing/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'billing')->name('billing.destroy');
    Route::get('/users', [CentroPageController::class, 'index'])->defaults('section', 'users')->name('users.index');
    Route::post('/users', [CentroPageController::class, 'store'])->defaults('section', 'users')->name('users.store');
    Route::get('/users/{id}', [CentroPageController::class, 'show'])->defaults('section', 'users')->name('users.show');
    Route::put('/users/{id}', [CentroPageController::class, 'update'])->defaults('section', 'users')->name('users.update');
    Route::post('/users/{id}/avatar', [CentroPageController::class, 'updateUserAvatar'])->name('users.avatar.update');
    Route::delete('/users/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'users')->name('users.destroy');
    Route::get('/settings', [CentroPageController::class, 'index'])->defaults('section', 'settings')->name('settings.index');
    Route::post('/settings/services', [CentroPageController::class, 'store'])->defaults('section', 'settings')->name('settings.store');
    Route::put('/settings/services/{id}', [CentroPageController::class, 'update'])->defaults('section', 'settings')->name('settings.update');
    Route::delete('/settings/services/{id}', [CentroPageController::class, 'destroy'])->defaults('section', 'settings')->name('settings.destroy');
    Route::put('/settings/document', [CentroPageController::class, 'updateDocumentSettings'])->name('settings.document.update');
    Route::put('/settings/email', [CentroPageController::class, 'updateEmailSettings'])->name('settings.email.update');
    Route::post('/settings/email/test', [CentroPageController::class, 'sendTestEmail'])->name('settings.email.test');
    Route::put('/settings/numbering/{id}', [CentroPageController::class, 'updateNumbering'])->name('settings.numbering.update');
    Route::post('/settings/backup', [CentroPageController::class, 'runBackup'])->name('settings.backup.run');
    Route::post('/settings/backup/{id}/restore', [CentroPageController::class, 'restoreBackup'])->name('settings.backup.restore');
    Route::delete('/settings/backup/{id}', [CentroPageController::class, 'destroyBackup'])->name('settings.backup.destroy');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.avatar.update');
    Route::post('/profile/absences', [ProfileController::class, 'storeAbsence'])->name('profile.absences.store');
    Route::delete('/profile/absences/{id}', [ProfileController::class, 'destroyAbsence'])->name('profile.absences.destroy');
    Route::get('/avatars/{filename}', [ProfileController::class, 'avatar'])->name('profile.avatar');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
